import js from "@eslint/js";
import tseslint from "typescript-eslint";
import jsdocPlugin from "eslint-plugin-jsdoc";
import importPlugin from "eslint-plugin-import";
import preferArrowPlugin from "eslint-plugin-prefer-arrow";
import stylistic from "@stylistic/eslint-plugin";
import globals from "globals";

export default tseslint.config(
    // Global ignores
    {
        ignores: [
            "**/parser/ANTLRv4*.ts",
            "**/parser/LexBasic.ts",
            "jest.config.ts",
            "out/**",
            "eslint.config.js",
            "misc/railroad-diagrams.js",
        ],
    },

    // Base recommended configs
    js.configs.recommended,
    jsdocPlugin.configs["flat/recommended"],

    // Main project config (type-checked rules scoped to .ts files only)
    ...tseslint.configs.recommendedTypeChecked.map((config) => ({
        ...config,
        files: ["**/*.ts"],
    })),
    {
        files: ["**/*.ts"],
        languageOptions: {
            parserOptions: {
                project: ["tsconfig.json", "src/webview-scripts/tsconfig.json"],
                tsconfigRootDir: import.meta.dirname,
            },
            globals: {
                ...globals.browser,
                ...globals.node,
                ...globals.jest,
                NodeJS: true,
            },
        },
        plugins: {
            "prefer-arrow": preferArrowPlugin,
            "import": importPlugin,
            "@stylistic": stylistic,
        },
        rules: {
            // Some base rules must be disabled as they return wrong results.
            // There are specialized TypeScript-specific rules instead.
            "no-explicit-any": "off",
            "no-use-before-define": "off",
            "no-shadow": "off",
            "array-callback-return": "warn",
            "default-case": ["warn", { commentPattern: "^no default$" }],
            "dot-location": ["warn", "property"],
            "eqeqeq": ["error", "smart"],
            "new-parens": "error",
            "no-array-constructor": "warn",
            "no-caller": "error",
            "no-cond-assign": "error",
            "no-const-assign": "warn",
            "no-control-regex": "warn",
            "no-delete-var": "warn",
            "no-dupe-args": "warn",
            "no-dupe-class-members": "off",
            "no-dupe-keys": "warn",
            "no-duplicate-case": "warn",
            "no-empty-character-class": "warn",
            "no-empty-pattern": "warn",
            "no-eval": "error",
            "no-ex-assign": "warn",
            "no-extend-native": "warn",
            "no-extra-bind": "warn",
            "no-extra-label": "warn",
            "no-fallthrough": ["warn", { commentPattern: "\\[falls?-through\\]" }],
            "no-func-assign": "warn",
            "no-implied-eval": "warn",
            "no-invalid-regexp": "warn",
            "no-iterator": "warn",
            "no-label-var": "warn",
            "no-labels": ["warn", { allowLoop: true, allowSwitch: false }],
            "no-lone-blocks": "warn",
            "no-loop-func": "warn",
            "no-mixed-operators": ["warn", {
                groups: [
                    ["&", "|", "^", "~", "<<", ">>", ">>>"],
                    ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
                    ["&&", "||"],
                    ["in", "instanceof"],
                ],
                allowSamePrecedence: false,
            }],
            "no-multi-str": "warn",
            "no-global-assign": "warn",
            "no-unsafe-negation": "warn",
            "no-new-func": "warn",
            "no-object-constructor": "warn",
            "no-new-native-nonconstructor": "warn",
            "no-new-wrappers": "error",
            "no-obj-calls": "warn",
            "no-octal": "warn",
            "no-octal-escape": "warn",
            "no-redeclare": ["warn", { builtinGlobals: false }],
            "no-regex-spaces": "warn",
            "no-restricted-syntax": ["warn", "WithStatement"],
            "no-script-url": "warn",
            "no-self-assign": "warn",
            "no-self-compare": "warn",
            "no-sequences": "warn",
            "no-shadow-restricted-names": "warn",
            "no-sparse-arrays": "warn",
            "no-template-curly-in-string": "warn",
            "no-this-before-super": "warn",
            "no-throw-literal": "error",
            "no-undef": "off",
            "no-restricted-globals": [
                "error",
                "addEventListener", "blur", "close", "closed", "confirm",
                "defaultStatus", "defaultstatus", "event", "external", "find",
                "focus", "frameElement", "frames", "history", "innerHeight",
                "innerWidth", "length", "location", "locationbar", "menubar",
                "moveBy", "moveTo", "name", "onblur", "onerror", "onfocus",
                "onload", "onresize", "onunload", "open", "opener", "opera",
                "outerHeight", "outerWidth", "pageXOffset", "pageYOffset",
                "parent", "print", "removeEventListener", "resizeBy", "resizeTo",
                "screen", "screenLeft", "screenTop", "screenX", "screenY",
                "scroll", "scrollbars", "scrollBy", "scrollTo", "scrollX",
                "scrollY", "self", "status", "statusbar", "stop", "toolbar", "top",
            ],
            "no-unreachable": "warn",
            "no-unused-expressions": "off",
            "no-unused-labels": "error",
            "no-unused-vars": "off",
            "no-useless-computed-key": "warn",
            "no-useless-concat": "warn",
            "no-useless-constructor": "off",
            "no-useless-escape": "warn",
            "no-useless-rename": ["warn", {
                ignoreDestructuring: false,
                ignoreImport: false,
                ignoreExport: false,
            }],
            "no-with": "warn",
            "no-whitespace-before-property": "warn",
            "no-constant-condition": "off",
            "require-yield": "warn",
            "rest-spread-spacing": ["warn", "never"],
            "strict": ["warn", "never"],
            "unicode-bom": ["warn", "never"],
            "use-isnan": "error",
            "valid-typeof": "off",
            "no-restricted-properties": [
                "error",
                {
                    object: "require",
                    property: "ensure",
                    message: "Please use import() instead.",
                },
                {
                    object: "System",
                    property: "import",
                    message: "Please use import() instead.",
                },
            ],
            "getter-return": "warn",
            "arrow-body-style": ["error", "always"],
            "arrow-parens": ["error", "always"],
            "camelcase": "off",
            "comma-dangle": ["error", "always-multiline"],
            "complexity": "off",
            "constructor-super": "error",
            "curly": "error",
            "dot-notation": "error",
            "eol-last": "error",
            "guard-for-in": "off",
            "id-denylist": ["error", "any", "number", "string", "boolean"],
            "id-match": "error",
            "import/order": "off",
            "import/no-webpack-loader-syntax": "off",
            "max-classes-per-file": ["error", 1],
            "max-len": ["error", {
                ignoreRegExpLiterals: false,
                ignoreStrings: false,
                code: 120,
            }],
            "newline-per-chained-call": "off",
            "no-bitwise": "off",
            "no-console": "off",
            "no-debugger": "off",
            "no-duplicate-imports": "error",
            "no-empty": "error",
            "no-invalid-this": "off",
            "no-magic-numbers": "off",
            "no-multiple-empty-lines": "error",
            "no-return-await": "error",
            "no-trailing-spaces": "error",
            "no-undef-init": "error",
            "no-underscore-dangle": "error",
            "no-unsafe-finally": "error",
            "object-shorthand": "error",
            "one-var": ["error", "never"],
            "padding-line-between-statements": [
                "error",
                { blankLine: "always", prev: "*", next: "return" },
            ],
            "prefer-arrow/prefer-arrow-functions": ["warn", {
                disallowPrototype: true,
                singleReturnOnly: false,
                classPropertiesAllowed: false,
            }],
            "prefer-template": "off",
            "quotes": "off",
            "quote-props": ["error", "consistent-as-needed"],
            "radix": "error",
            "space-before-function-paren": "off",
            "spaced-comment": ["off", "never"],
            "indent": "off",

            // TypeScript-specific rules
            "@typescript-eslint/no-unused-vars": ["warn", {
                args: "after-used",
                ignoreRestSiblings: true,
                varsIgnorePattern: "^_",
                argsIgnorePattern: "^_",
            }],
            "@typescript-eslint/no-non-null-assertion": "off",
            "@typescript-eslint/array-type": ["error", { default: "array-simple" }],
            "@typescript-eslint/consistent-type-definitions": "error",
            "@typescript-eslint/explicit-member-accessibility": ["error", {
                accessibility: "explicit",
            }],
            "@stylistic/indent": ["error", 4, {
                ignoreComments: true,
                SwitchCase: 1,
                MemberExpression: 1,
            }],
            "@typescript-eslint/member-ordering": ["error", {
                default: [
                    "signature",
                    "public-static-field",
                    "protected-static-field",
                    "private-static-field",
                    "public-decorated-field",
                    "protected-decorated-field",
                    "private-decorated-field",
                    "public-instance-field",
                    "protected-instance-field",
                    "private-instance-field",
                    "public-abstract-field",
                    "protected-abstract-field",
                    "public-field",
                    "protected-field",
                    "private-field",
                    "static-field",
                    "instance-field",
                    "abstract-field",
                    "decorated-field",
                    "field",
                    "public-constructor",
                    "protected-constructor",
                    "private-constructor",
                    "constructor",
                    "public-static-method",
                    "protected-static-method",
                    "private-static-method",
                    "public-decorated-method",
                    "protected-decorated-method",
                    "private-decorated-method",
                    "public-instance-method",
                    "protected-instance-method",
                    "private-instance-method",
                    "public-abstract-method",
                    "protected-abstract-method",
                ],
            }],
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-use-before-define": "error",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-call": "error",
            "@typescript-eslint/no-unsafe-return": "error",
            "@typescript-eslint/explicit-module-boundary-types": "error",
            "@typescript-eslint/prefer-for-of": "error",
            "@typescript-eslint/prefer-function-type": "error",
            "@stylistic/quotes": ["error", "double", {
                avoidEscape: true,
                allowTemplateLiterals: "always",
            }],
            "@stylistic/semi": ["error", "always"],
            "@typescript-eslint/unified-signatures": "error",
            "@typescript-eslint/prefer-regexp-exec": "off",
            "@typescript-eslint/naming-convention": [
                "error",
                {
                    selector: "default",
                    format: ["camelCase"],
                    filter: { regex: "^_", match: false },
                },
                { selector: "class", format: ["PascalCase"] },
                { selector: "typeParameter", format: ["PascalCase"] },
                { selector: "enum", format: ["PascalCase"] },
                { selector: ["enumMember"], format: ["PascalCase"] },
                {
                    selector: ["classProperty"],
                    modifiers: ["static"],
                    format: ["PascalCase", "camelCase"],
                },
                { selector: "typeAlias", format: ["PascalCase"] },
                {
                    selector: "interface",
                    format: ["PascalCase"],
                    prefix: ["I"],
                },
            ],
            "@typescript-eslint/no-unsafe-enum-comparison": "off",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/triple-slash-reference": "off",

            // Formatting rules replacing tslint import-spacing, one-line, whitespace
            "@stylistic/keyword-spacing": ["error", { before: true, after: true }],
            "@stylistic/brace-style": ["error", "1tbs", { allowSingleLine: true }],

            // JSDoc rules
            "jsdoc/check-alignment": "error",
            "jsdoc/check-indentation": "off",
            "jsdoc/require-param-type": "off",
            "jsdoc/require-returns-type": "off",
            "jsdoc/tag-lines": "off",
        },
    },
);
